COMPONENTS = {
    
    "Core" : [
        "JiojuDB.Reference",
        "JiojuDB.Serializer",
        "JiojuDB.Serializer.JSON",
        
        "JiojuDB.TypeMap",
        "JiojuDB.TypeMap.Feature.NoDeps",
        "JiojuDB.TypeMap.Array",
        "JiojuDB.TypeMap.Object",
        "JiojuDB.TypeMap.Joose",
        
        "JiojuDB.Resolver",
        "JiojuDB.Resolver.Standard",
        
        "JiojuDB.Collapser.Inliner",
        "JiojuDB.Collapser.Inliner.JSPON",
        
        "JiojuDB.Backend",
        "JiojuDB.Backend.Hash",
        
        "JiojuDB.Node",
        "JiojuDB.Collapser",
        
        "JiojuDB.LiveObjects",
        "JiojuDB"
    ]
    
} 

