COMPONENTS = {
    
    "Core" : [
        "KiokuJS.Reference",
        "KiokuJS.Serializer",
        "KiokuJS.Serializer.JSON",
        
        "KiokuJS.TypeMap",
        "KiokuJS.TypeMap.Feature.NoDeps",
        "KiokuJS.TypeMap.Array",
        "KiokuJS.TypeMap.Object",
        "KiokuJS.TypeMap.Joose",
        
        "KiokuJS.Resolver",
        "KiokuJS.Resolver.Standard",
        
        "KiokuJS.Collapser.Inliner",
        "KiokuJS.Collapser.Inliner.JSPON",
        
        "KiokuJS.Backend",
        "KiokuJS.Backend.Hash",
        
        "KiokuJS.Node",
        "KiokuJS.Collapser",
        
        "KiokuJS.Scope",
        "KiokuJS"
    ]
} 

